### ISSUE TITLE
Remove the Combat Pets config from public access

### ISSUE THREAD

**Issue by JoyfulKoinu** [Cheu3172/CA#13]
Players can view and access the database using the stored plaintext passcodes within the config file
`Database:
  Type: SQLite
  Auto_Save_Interval: 15
  Instant_Save: true
  MySQL:
    Username: user123
    Password: pass123
    Host: localhost:3306
    Database: server
  Purge:
    Enabled: false
    For_Inactive_Days: 60
  Sync_Interval: 60`

**Comment by Cheu3172** [comment]
SQLLite Database is not activated, player's cannot access any server-side data using this.
